In [4]:
from transformers import Transformer
import torch
import torch.nn as nn

In [65]:
device = 'cpu' #torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([
            [1, 5, 6, 4, 3, 9, 5, 2, 0],
            [1, 8, 7, 3, 4, 5, 6, 7, 2]
                ]).to(device)

x0 = torch.tensor([
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [1, 8, 7, 3, 4, 5, 6, 7, 2]
                ]).to(device)
trg = torch.tensor([
            [1, 7, 4, 3, 5, 9, 2, 0],
            [1, 5, 6, 2, 4, 7, 6, 2]
                ]).to(device)

src_pad_idx = 0
trg_pad_idx = 0
src_vocab_size = 10
trg_vocab_size = 10

model = Transformer(
        src_vocab_size,
        trg_vocab_size,
        src_pad_idx,
        trg_pad_idx,
        device=device
                    ).to(device)

In [66]:
x.shape

torch.Size([2, 9])

In [67]:
trg[:, :-1], trg[:, :-1].shape, trg.shape

(tensor([[1, 7, 4, 3, 5, 9, 2],
         [1, 5, 6, 2, 4, 7, 6]]),
 torch.Size([2, 7]),
 torch.Size([2, 8]))

In [68]:
model(x[:, :-2], trg[:, :-1])[0]

tensor([[-0.3299, -0.9455, -0.4432, -1.1032, -0.0143,  0.0863, -0.5562, -0.5071,
          0.0025,  0.3875],
        [-0.2193,  0.1459,  0.0578, -1.0030,  0.1935,  0.1004, -0.2461, -0.6875,
          0.3093,  0.6319],
        [-0.4411, -0.4814, -0.7593, -0.8522,  0.0884,  0.9218, -0.8620, -0.6481,
          0.4670, -0.4856],
        [-1.0341, -0.3689,  0.1061,  0.2436,  0.5519, -0.2100, -0.8712,  0.0567,
         -0.3093,  1.1816],
        [-0.4440, -0.8197, -0.2595, -0.5893, -0.0886,  0.1281, -0.9936, -1.8873,
          0.1936, -0.9485],
        [-0.9687,  0.3648, -0.6937, -0.0388, -0.3577, -0.3664, -1.4643, -0.3819,
          1.2589,  0.2598],
        [ 0.2474, -0.2774, -1.2459, -0.8634, -0.3968, -0.0247, -0.9729, -0.5809,
          0.2782,  0.4028]], grad_fn=<SelectBackward0>)

In [73]:
model(x0[:, :-2], trg[:, :-2])[0]

tensor([[ 0.3567, -0.5561, -0.6778, -1.1785, -0.1347,  0.2910, -0.9880, -0.0993,
         -0.5660,  0.1328],
        [ 0.3511,  0.4719, -0.2511, -1.0957,  0.0651,  0.4783, -0.6951, -0.4522,
         -0.3153,  0.3716],
        [ 0.3098, -0.0091, -0.8179, -0.9697, -0.0577,  1.0629, -1.1236, -0.3785,
         -0.3261, -0.6616],
        [-0.3216, -0.0347, -0.1215,  0.1859,  0.3932,  0.1305, -1.2242,  0.2934,
         -1.0580,  0.8651],
        [ 0.2365, -0.2893, -0.5983, -0.6762, -0.0602,  0.3839, -1.5148, -1.4460,
         -0.3303, -1.0405],
        [-0.2012,  0.6639, -1.0010, -0.2271, -0.3721,  0.0323, -1.9351, -0.1304,
          0.5268,  0.0940]], grad_fn=<SelectBackward0>)

In [61]:
_ = model.train(mode=True)

In [49]:
vars(model)

{'training': False,
 '_parameters': OrderedDict(),
 '_buffers': OrderedDict(),
 '_non_persistent_buffers_set': set(),
 '_backward_pre_hooks': OrderedDict(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_hooks_with_kwargs': OrderedDict(),
 '_forward_hooks_always_called': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_forward_pre_hooks_with_kwargs': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_load_state_dict_post_hooks': OrderedDict(),
 '_modules': OrderedDict([('encoder',
               Encoder(
                 (word_embedding): Embedding(100, 256)
                 (position_embedding): Embedding(100, 256)
                 (layers): ModuleList(
                   (0-5): 6 x TransformerBlock(
                     (attention): SelfAttention(
                       (values): Linear(in_features=32, out_features=32, bia

In [36]:
out = model(x[:, :-2], trg[:, :-1])
print(out)
print(out.shape)

tensor([[[ 1.0239,  0.4032,  0.4141, -0.5993, -0.1736, -0.2945,  0.3026,
          -0.2899, -0.1778, -0.4827],
         [ 0.3920, -0.0982, -0.2291,  0.5510,  0.2726,  0.7251,  0.5545,
           0.2318, -0.1314, -0.6601],
         [ 0.1243, -0.2480,  0.2311, -0.7781,  0.0332,  0.2505,  0.6322,
           1.2396, -0.0157, -0.6503],
         [ 0.2661, -0.6432, -0.2973, -0.7532, -0.3159, -0.0192, -0.0825,
           0.4322,  0.0517, -0.6020],
         [ 0.6415, -0.1725,  0.4561, -0.3545, -0.2782,  0.0218, -1.0065,
           0.0048,  0.1238, -0.3268],
         [ 0.1579, -0.5693,  0.4820, -0.3092, -0.3181,  0.1356, -0.2002,
           1.2272,  0.6198, -1.0544],
         [ 1.1024,  0.0890,  0.6984, -0.1608,  0.3280,  0.2453,  0.2567,
           0.3979,  0.5171, -0.1645]],

        [[ 1.0027,  0.4580,  0.4955, -0.4880, -0.2184, -0.4111,  0.2063,
          -0.5721, -0.1969, -0.5896],
         [ 0.7461, -0.3191,  0.1018, -0.1082, -0.4229,  1.2341,  0.1967,
           0.2269, -0.5271, -0.6328],