In [1]:
import torch
import torch.nn as nn

In [41]:
lin = nn.Linear(2, 1, bias=False)
print(lin,)
lin_weigth = lin.weight
lin_weigth

Linear(in_features=2, out_features=1, bias=False)


Parameter containing:
tensor([[ 0.2006, -0.2199]], requires_grad=True)

In [54]:
lin.state_dict()['weight']

tensor([[ 0.2006, -0.2199]])

In [42]:
print(f"{lin_weigth[0][0]=}, {lin_weigth[0][1]=}")

lin_weigth[0][0]=tensor(0.2006, grad_fn=<SelectBackward0>), lin_weigth[0][1]=tensor(-0.2199, grad_fn=<SelectBackward0>)


In [43]:
x = torch.randn(1, 2,)
print(x.shape)
x

torch.Size([1, 2])


tensor([[ 1.3708, -0.5943]])

In [44]:
lin(x)

tensor([[0.4056]], grad_fn=<MmBackward0>)

In [45]:
print(f"{x[0][0]=}, {x[0][1]=}")

x[0][0]=tensor(1.3708), x[0][1]=tensor(-0.5943)


In [47]:
x[0][0]*lin_weigth[0][0]

tensor(0.2749, grad_fn=<MulBackward0>)

In [48]:
x[0][1]*lin_weigth[0][1]

tensor(0.1307, grad_fn=<MulBackward0>)

In [55]:
x[0][0]*lin_weigth[0][0] + x[0][1]*lin_weigth[0][1]

tensor(0.4056, grad_fn=<AddBackward0>)