In [2]:
import torch
import torch.nn as nn

In [19]:
n_embed = 12
head_size = 2

block_size = 8

In [20]:
B,T,C = 4,8,2 # batch, time, channels

In [23]:
x = torch.randn(B,T,C)
x[0]

tensor([[-0.7908,  0.6358],
        [-0.9635,  2.6399],
        [-1.1668,  0.2296],
        [-0.2602,  0.3668],
        [ 0.2402, -1.7208],
        [ 0.3466,  0.4891],
        [ 1.8997, -0.7657],
        [ 0.6791,  0.5573]])

In [24]:
tril = torch.tril(torch.ones(T, T))
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
values = nn.Linear(C, head_size, bias=False)

In [28]:
# B, T, C = x.shape
k = key(x)
k[0]
# q = query(x)

tensor([[-0.5695, -0.7769],
        [-1.0560, -2.2603],
        [-0.7027, -0.6474],
        [-0.2180, -0.3666],
        [ 0.4696,  1.3119],
        [ 0.1005, -0.2002],
        [ 1.2201,  1.3300],
        [ 0.2748, -0.1098]], grad_fn=<SelectBackward0>)

In [29]:
key.weight

Parameter containing:
tensor([[ 0.5640, -0.1942],
        [ 0.4163, -0.7043]], requires_grad=True)

In [34]:
x[0] # key

tensor([[-0.7908,  0.6358],
        [-0.9635,  2.6399],
        [-1.1668,  0.2296],
        [-0.2602,  0.3668],
        [ 0.2402, -1.7208],
        [ 0.3466,  0.4891],
        [ 1.8997, -0.7657],
        [ 0.6791,  0.5573]])

In [17]:
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])